apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress
  labels: 
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - image: googlecontainer/nginx-ingress:1.0
        name: nginx 
        ports:
        - containerPort: 80
          hostPort: 80
